include:
  - apps/aiometadata/compose.yaml
  - apps/aiostreams/compose.yaml
  - apps/authelia/compose.yaml
  - apps/crowdsec/compose.yaml
  - apps/nzbhydra2/compose.yaml
  - apps/stremthru/compose.yaml
  - apps/syncio/compose.yaml
  - apps/traefik/compose.yaml
  - apps/watchtower/compose.yaml

networks:
  default:
    name: ${DOCKER_NETWORK:-aiostreams}
    external: ${DOCKER_NETWORK_EXTERNAL:-false}
